services:
  planning:
    network_mode: host
    runtime: nvidia
    ipc: host
    volumes:
      # 分別掛載開發的 Package，避免覆蓋掉被放在 src 中的 urg_node2
      - /home/systemlabagx/disk/agx/planning/src/car_control:/root/ros2_ws/src/car_control
      - /home/systemlabagx/disk/agx/planning/src/rl_navigator:/root/ros2_ws/src/rl_navigator
      - /home/systemlabagx/disk/agx/planning/src/models:/root/ros2_ws/src/models
      - /home/systemlabagx/disk/agx/cosmos/VLA:/root/ros2_ws/src/vla_demo
      - /dev/bus/usb:/dev/bus/usb
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
      - "/dev/video2:/dev/video2"
      - "/dev/video3:/dev/video3"
      - "/dev/video4:/dev/video4"
      - "/dev/video5:/dev/video5"
      - "/dev/media0:/dev/media0"
      - "/dev/media1:/dev/media1"
      - "/dev/media2:/dev/media2"
