services:
  # =========================================
  # ROS 1 <-> ROS 2 橋樑 (Bridge)
  # =========================================
  bridge:
    platform: ${ARCH:-linux/amd64}
    build:
      context: ./
      dockerfile: Dockerfile
    image: agx_ros/bridge:latest
    container_name: bridge
    restart: unless-stopped
    depends_on:
      - roscore
    environment:
      - ROS_MASTER_URI=http://roscore:11311
      - ROS_HOSTNAME=bridge
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - FASTRTPS_DEFAULT_PROFILES_FILE=/fastdds.xml
    tty: true
    stdin_open: true
    command: [ "/entrypoint.sh" ]
